In [ ]:
import numpy as np

def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

X = np.array([[0.2, 0.1],
              [0.2, 0.3],
              [-0.2, -0.3]])

y = np.array([[0.7],
              [0.4],
              [0.65]])

weights_1 = np.random.random((2, 3)) - 0.5
weights_2 = np.random.random((3, 2)) - 0.5
weights_3 = np.random.random((2, 1)) - 0.5

print("------Вагові коефіціенти до навчання-----")
print("weights_1")
print(weights_1)
print("weights_2")
print(weights_2)
print("weights_3")
print(weights_3)

result_error = 0;

num_iterations = 10000

for i in range(num_iterations):

    layer_1 = tanh(np.dot(X, weights_1))
    layer_2 = tanh(np.dot(layer_1, weights_2))
    layer_3 = tanh(np.dot(layer_2, weights_3))


    error = y - layer_3

    layer_3_gradient = error * tanh_derivative(layer_3)
    layer_2_gradient = layer_3_gradient.dot(weights_3.T) * tanh_derivative(layer_2)
    layer_1_gradient = layer_2_gradient.dot(weights_2.T) * tanh_derivative(layer_1)

    weights_3 += layer_2.T.dot(layer_3_gradient)
    weights_2 += layer_1.T.dot(layer_2_gradient)
    weights_1 += X.T.dot(layer_1_gradient)

    result_error = error

print("Результати після навчання:")

print("------Вагові коефіціенти-----")
print("weights_1")
print(weights_1)
print("weights_2")
print(weights_2)
print("weights_3")
print(weights_3)

print("------Досягнуте значення помилки-----")

print(result_error)

print("Порівняння виходів (у) та вихідних данних за результатами навчання (layer_3)")
print(y)
print(layer_3)

------Вагові коефіціенти до навчання-----
weights_1
[[-0.37298201  0.44808762 -0.49565096]
 [ 0.49421669 -0.46822198  0.30861053]]
weights_2
[[ 0.20413067  0.17261349]
 [-0.26105055  0.47673123]
 [-0.46565709  0.27967713]]
weights_3
[[ 0.19164271]
 [-0.02225478]]
Результати після навчання:
------Вагові коефіціенти-----
weights_1
[[-0.95040639  0.70490353 -2.45997548]
 [ 0.70998614 -0.55260618  1.75520731]]
weights_2
[[-0.50273335  0.30374237]
 [ 0.48192779  0.34222827]
 [-1.43268807  0.48176644]]
weights_3
[[ 1.65429047]
 [-0.34092087]]
------Досягнуте значення помилки-----
[[2.55351296e-15]
 [5.25000000e-01]
 [5.25000000e-01]]
Порівняння виходів (у) та вихідних данних за результатами навчання (layer_3)
[[0.7 ]
 [0.4 ]
 [0.65]]
[[ 0.7  ]
 [-0.125]
 [ 0.125]]
